120 fix readmi
Nikemaks/DevNoteProximity pull request #139
Opened 2024-05-14 22:01 UTC by YaroslavOkrema

2024-05-14 22:08 UTC, Nikemaks requested changes

2024-05-14 22:08 UTC, Nikemaks commented on README.md
>  # DevNoteProximity
Please return this: 
[![Angular GitHub CI/CD](https://github.com/Nikemaks/DevNoteProximity/actions/workflows/main.yaml/badge.svg)](https://github.com/Nikemaks/DevNoteProximity/actions/workflows/main.yaml)

2024-05-15 11:09 UTC, Roman15122022 approved these changes

2024-05-15 12:14 UTC, Nikemaks approved these changes

2024-05-15 12:15 UTC, merged